# Generated by Django 2.0.3 on 2018-08-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wargame_admin", "0001_initial")]

    operations = [migrations.DeleteModel(name="Config")]
