# Generated by Django 2.0.3 on 2018-08-15 16:43

from django.db import migrations


def update_config(apps, schema_editor):
    Config = apps.get_model('wargame_admin', 'Config')
    version_switch = Config(key='qpa_hack',
                            value='qpa',
                            display_name='QPA/Hacktivity',
                            description='Switches the flags between QPA and Hacktivity versions',
                            possible_values='["qpa", "hacktivity"]')
    version_switch.save()
    stage_tasks = Config(key='stage_tasks',
                         value='5',
                         display_name='Tasks per stage',
                         description='Number of completed tasks needed before the next stage is unlocked')
    stage_tasks.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wargame_admin', '0003_config'),
    ]

    operations = [
        migrations.RunPython(update_config)
    ]
