# Generated by Django 2.1.2 on 2018-10-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("wargame_admin", "0008_challengefilechunkedupload")]

    operations = [
        migrations.RemoveField(model_name="challengefilechunkedupload", name="config_name"),
        migrations.RemoveField(model_name="challengefilechunkedupload", name="display_name"),
        migrations.RemoveField(model_name="challengefilechunkedupload", name="private"),
    ]
