# Generated by Django 2.1.5 on 2019-02-04 22:40

from django.db import migrations


def update_config(apps, schema_editor):
    Config = apps.get_model('wargame_admin', 'Config')

    require_email = Config(key='email_required',
                           value='False',
                           display_name='Email required',
                           description='Require that the user provide an email address when creating a new account.',
                           possible_values='["True", "False"]')

    require_email.save()


class Migration(migrations.Migration):
    dependencies = [
        ('wargame_admin', '0009_auto_20181011_1350'),
    ]

    operations = [
        migrations.RunPython(update_config)
    ]
