# Generated by Django 2.1.5 on 2019-02-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame_admin", "0010_auto_20190204_2340")]

    operations = [
        migrations.CreateModel(
            name="StaticContent",
            fields=[
                ("key", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("display_name", models.CharField(max_length=255)),
                ("html", models.TextField()),
            ],
        )
    ]
