# Generated by Django 2.1.5 on 2019-02-05 06:30

from django.db import migrations


def update_config(apps, schema_editor):
    StaticContent = apps.get_model('wargame_admin', 'StaticContent')

    index_right = StaticContent(
        key='index_right',
        display_name='Right side of the homepage',
        html="""<p style="background-color: red; color: white; padding: 1em; border-radius: 5px;"><b>Notice:</b> the game has ended for this year but we have re-opened it upon several user requests. <b>The game comes with absolutely no support, just as is!</b> In case something gets broken, remains broken.</p>
        <h3>Welcome every hacker at this year's Wargame!</h3>
        <p>Every new stage is unlocked by solving 3 challenges on the previous stage. The solution of every assignment is a 32 characters long MD5 hash wrapped into "SECURITEAM{...}" (e.g. "SECURITEAM{0123456789abcdef0123456789abcdef}"). If you find the hash without the pre- and postfixes, then you should wrap it in yourself.</p>
        <p>The hint button gives you some help but will halve the score of the challenge.</p>
        <p style="font-weight: bold;">To reach the *.wargame sites, see the instructions in the VPN menu.</p>
        <p style="text-align: center">Questions/Info: <code>---</code></p>
        <h3 style="text-align: center">There are more challenges, too!</h3>
        <p>As this game is co-organized by the Hackerspace Szeged, you can solve multiple challenges created by them. <b>The ones marked with #HackespaceSzeged# do NOT use our flag format!</b></p>"""
    )
    index_right.save()

    rules = StaticContent(
        key="rules",
        display_name="Rules page",
        html="""<ol>
        <li>Attacking the scoring, or handling system is strictly probihited, and will result in the cancellation of your account</li>
        <li>The wargame is open during the Hacktivity.</li>
        <li>Players can get a hint for each challenge but doing so will halve the available score of the challenge.</li>
        <li>For further rules, please refer to the organizers of the Hacktivity.</li>
    </ol>"""
    )
    rules.save()

    links = StaticContent(
        key="links",
        display_name="Links page",
        html="""<ul>
        <li><a href="http://hax.tor.hu">hax.tor.hu</a> </li>
        <li><a href="http://hackthissite.org/">hackthissite.org</a> </li>
        <li><a href="http://try2hack.nl/">try2hack.nl</a> </li>
        <li><a href="http://kszk.sch.bme.hu/">kszk.sch.bme.hu</a> </li>
    </ul>"""
    )
    links.save()

    vpn = StaticContent(
        key="vpn",
        display_name="VPN page",
        html="""<a href="/vpn/key">Download keys and configuration</a>
    <p>
        You need to connect to the wargame network to be able to access our challenge servers. For that you need OpenVPN installed on your computer. On Windows, you can <a href="https://openvpn.net/index.php/download/community-downloads.html" target="_blank">download OpenVPN from here</a>. On Linux, it's most likely provided by your distributions package manager.
    </p>
    <p>
        After you have successfully installed OpenVPN, you need to configure it to connect to our VPN service. We use TLS and we provide a keypair for each user, a certificate for our internal CA which you should trust for the context of the VPN connection, and an example configuration file which you can use with OpenVPN directly. You can download the package <a href="/vpn/key">here</a>.
    </p>
    <p>
        On Windows you may have to change the extension of the config file to .ovpn to use it with the Windows client.
    </p>
    <p>
        On Linux, you can use the client config file directly, like this:
    </p>
    <p><code>
        openvpn --config client.conf
    </code></p>
<p>DNS is not working? Use these IPs instead of domain names:</p>
<table>
    <tr>
        <th>brainfuck.wargame</th>
        <th>10.13.37.206</th>
    </tr>
    <tr>
        <th>cattags.wargame</th>
        <th>10.13.37.201</th>
    </tr>
    <tr>
        <th>colorful.wargame</th>
        <th>10.13.37.207</th>
    </tr>
    <tr>
        <th>flagdownloader.wargame</th>
        <th>10.13.37.203</th>
    </tr>
    <tr>
        <th>motivation.wargame</th>
        <th>10.13.37.208</th>
    </tr>
    <tr>
        <th>poloshop.wargame</th>
        <th>10.13.37.205</th>
    </tr>
    <tr>
        <th>story.wargame</th>
        <th>10.13.37.202</th>
    </tr>
</table>"""
    )
    vpn.save()

    email_notification = StaticContent(
        key="email_notification",
        display_name="Email notification text",
        html="""As you might already know, the best teams get to compete in the Speed Hacking. To allow us to notify you in case you are one of them, please give us your email address, by clicking <a href='/user/set-email'>here</a>."""
    )
    email_notification.save()


class Migration(migrations.Migration):
    dependencies = [
        ('wargame_admin', '0011_staticcontent'),
    ]

    operations = [
        migrations.RunPython(update_config)
    ]
