# Generated by Django 2.2.2 on 2019-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame_admin", "0013_export")]

    operations = [
        migrations.AddField(model_name="staticcontent", name="note", field=models.CharField(default="", max_length=255))
    ]
