# Generated by Django 3.1.2 on 2020-10-04 19:12

from django.db import migrations


def update_config(apps, schema_editor):
    Config = apps.get_model("wargame_admin", "Config")

    require_email = Config(
        key="private_scoreboard",
        value="False",
        display_name="Private scoreboard",
        description="Hides to scoreboard to non-admins",
        possible_values='["True", "False"]',
    )

    require_email.save()


class Migration(migrations.Migration):
    dependencies = [
        ('wargame_admin', '0015_auto_20190617_1527'),
    ]

    operations = [
        migrations.RunPython(update_config)
    ]
