# Generated by Django 2.0.3 on 2018-03-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('creation_dt', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=4096)),
            ],
        ),
    ]
