# Generated by Django 2.0.3 on 2018-04-11 20:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [("wargame", "0001_initial")]

    operations = [migrations.AlterField(model_name="challenge", name="description", field=markdownx.models.MarkdownxField())]
