# Generated by Django 2.0.3 on 2018-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame", "0002_auto_20180411_2227")]

    operations = [
        migrations.AddField(
            model_name="challenge", name="short_description", field=models.CharField(default="", max_length=512)
        )
    ]
