# Generated by Django 2.0.3 on 2018-07-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0004_staffmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_hacktivity',
            field=models.CharField(max_length=256, null=True, verbose_name='Flag (Hacktivity)'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='flag_qpa',
            field=models.CharField(max_length=256, null=True, verbose_name='Flag (QPA)'),
        ),
    ]
