# Generated by Django 2.0.3 on 2018-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame", "0006_file")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="display_name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        )
    ]
