# Generated by Django 2.1.5 on 2019-02-06 14:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wargame', '0012_auto_20190206_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
