# Generated by Django 2.1.5 on 2019-02-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0014_auto_20190206_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='solution',
            field=models.CharField(max_length=8192, null=True),
        ),
    ]
