# Generated by Django 2.1.5 on 2019-02-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargame', '0016_auto_20190206_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
