# Generated by Django 2.2.1 on 2019-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame", "0018_file_filename")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="import_name",
            field=models.CharField(max_length=64, unique=True, verbose_name="Internal name"),
        )
    ]
