# Generated by Django 2.2.2 on 2019-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wargame", "0019_auto_20190609_1408")]

    operations = [migrations.AddField(model_name="challenge", name="hidden", field=models.BooleanField(default=False))]
